"use client";

import { use } from "react";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import { useAcceptProposal, useProposal, useUpdateProposalStatus } from "@/hooks/use-ai-proposals";
import { ProposalStatusBadge } from "@/components/dashboard/ai/proposal-status-badge";
import type { UpdatableProposalStatus } from "@/types/ai";

export default function ProposalDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const { data: proposal, isLoading, error } = useProposal(id);
  const { mutate: updateStatus, isPending: isUpdating } = useUpdateProposalStatus(id);
  const { mutate: accept, isPending: isAccepting } = useAcceptProposal(id);

  if (isLoading) return <Skeleton className="h-64 w-full" />;
  if (error || !proposal) return <p className="text-sm text-destructive">Proposal not found.</p>;

  const canAccept = proposal.status === "SENT" || proposal.status === "DRAFT";

  return (
    <div className="max-w-2xl space-y-6">
      <Link href="/ai/proposals" className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:underline">
        <ArrowLeft className="h-4 w-4" /> Back to Proposals
      </Link>

      <div className="flex items-center justify-between">
        <h1 className="text-xl font-semibold">{proposal.title}</h1>
        <ProposalStatusBadge status={proposal.status} />
      </div>

      <Card>
        <CardHeader><CardTitle>Details</CardTitle></CardHeader>
        <CardContent className="space-y-2 text-sm">
          <p className="whitespace-pre-wrap text-muted-foreground">{proposal.content}</p>
          <div className="grid grid-cols-2 gap-2 pt-3">
            <span className="text-muted-foreground">Amount</span>
            <span>{proposal.amount ? `${proposal.amount} ${proposal.currency}` : "—"}</span>
            <span className="text-muted-foreground">Client</span>
            <span>{proposal.client?.companyName ?? "—"}</span>
            <span className="text-muted-foreground">Lead</span>
            <span>{proposal.lead?.name ?? "—"}</span>
            <span className="text-muted-foreground">Generated by</span>
            <span>{proposal.generatedBy?.name ?? "—"}</span>
          </div>
        </CardContent>
      </Card>

      <div className="flex items-center gap-3">
        {proposal.status !== "ACCEPTED" && (
          <Select
            value={proposal.status}
            onValueChange={(v) => updateStatus(v as UpdatableProposalStatus)}
            disabled={isUpdating || proposal.status === "REJECTED"}
          >
            <SelectTrigger className="w-40"><SelectValue /></SelectTrigger>
            <SelectContent>
              <SelectItem value="DRAFT">Draft</SelectItem>
              <SelectItem value="SENT">Sent</SelectItem>
              <SelectItem value="REJECTED">Rejected</SelectItem>
            </SelectContent>
          </Select>
        )}

        {canAccept && (
          <AlertDialog>
            <AlertDialogTrigger asChild>
              <Button disabled={isAccepting}>Accept &amp; Generate Invoice</Button>
            </AlertDialogTrigger>
            <AlertDialogContent>
              <AlertDialogHeader>
                <AlertDialogTitle>Accept this proposal?</AlertDialogTitle>
                <AlertDialogDescription>
                  This will mark the proposal as accepted and automatically generate an invoice
                  for the linked client. This cannot be undone.
                </AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel>Cancel</AlertDialogCancel>
                <AlertDialogAction onClick={() => accept()}>Accept</AlertDialogAction>
              </AlertDialogFooter>
            </AlertDialogContent>
          </AlertDialog>
        )}
      </div>
    </div>
  );
}